### ISSUE TITLE
Upload US Code Data to Google Public Data Explorer to Test Viability as Legal Analytics Tool

### ISSUE THREAD

**Issue by dazzaji** [HumanDynamics/FreeLaw#15]
Let's give this a try!  Code for America... here we come!

**Comment by jeffrey6557** [comment]
Let's try this Google example datasets: https://developers.google.com/public-data/docs/examples

**Comment by dazzaji** [comment]
Working with Chang we got a little closer using an ex file to test... here it is! 

http://www.google.com/publicdata/explore?ds=z1c78f936dj7t5_&ctype=b&strail=false&bcs=d&nselm=s&met_x=sales&fdim_x=business:44x72&scale_x=lin&ind_x=false&met_y=sales&fdim_y=business:44x72&scale_y=lin&ind_y=false&idim=seasonality:Not+Seasonally+Adjusted:Seasonally+Adjusted&ifdim=seasonality&ind=false&icfg&draft

**Comment by jeffrey6557** [comment]
Cann't open it. Error message: 
"Not Found

Error 404"

**Comment by dazzaji** [comment]
must be some sort of way to "share" or make it public (like Google Drive)... I found a similar issue in the DSPL forum recommending the data set be "published"... still looking for that ... https://groups.google.com/forum/#!topic/dspl-discuss/2Bjs41okkQg

**Comment by ShadovvMoon** [comment]
I can't actually test this (since any test datasets I try to upload get stuck in `pending`) but it might be under  `Sharing Settings` at http://www.google.com/publicdata/admin
![](http://www.samuco.net/blob/pdu.jpg)

**Comment by dazzaji** [comment]
I had the same issue but status went from Pending to Approved in a few minutes. How long has your submission been pending?

**Comment by ShadovvMoon** [comment]
roughly 20 minutes

**Comment by dazzaji** [comment]
is your upload still pending approval?

**Comment by jeffrey6557** [comment]
Understood the XML file after going through the tutorial and should be able to write one for our legal data. So my next step is to modify the XML file the tutorial example (with country, population and year) and then the dataset.

**Comment by ShadovvMoon** [comment]
still pending :disappointed:

**Comment by ShadovvMoon** [comment]
It finally finished Pending. Are you able to access this data?
http://www.google.com/publicdata/explore?ds=m9tpfkd301lnd_&ctype=l&strail=false&bcs=d&nselm=h&met_y=population&scale_y=lin&ind_y=false&rdim=country&idim=country:AF:US&ifdim=country&ind=false

**Comment by jeffrey6557** [comment]
Yes, perfectly.

**Comment by ShadovvMoon** [comment]
Ok, here's how I made it accessible:
1. Go to http://www.google.com/publicdata/admin
2. Click on 'Sharing Settings' next to the dataset
![](http://www.samuco.net/blob/shareset.png)

3. Under Visibility, select 'Public on the web' (and then click Change)
![](http://www.samuco.net/blob/public.png)

4. Select the dataset
![](http://www.samuco.net/blob/dset.png)

5. Select 'Explore the data'
![](http://www.samuco.net/blob/explore.png)

6. Click the link  button
![](http://www.samuco.net/blob/linky.png)

7. Copy/paste the link

**Comment by dazzaji** [comment]
Thanks for the walk through.  It's odd how long your upload status was "pending".  Should have updated this thread earlier that we were able to make the dataset public (using the same workflow you describe) but I switched back to private within a few minutes because the dataset was just for test purposes and might have caused confusion.  It looks like two of us have now successfully uploaded and shared data in a way that anybody can investigate using the Public Data Explorer... this is exactly what I'd hoped to confirm.

**Comment by dazzaji** [comment]
This is how it might look if we explored the rate of change (amendment, repeal, etc) of US Code Sections using Table 3 data from the US House.  Check out this [screen cast](https://files.zenhub.io/54bd9883f748cd180f079745) | uploaded just now.

**Comment by dazzaji** [comment]
I think we can close this issue/question and consider the answer to be: Yes.
